### ISSUE TITLE
Improve react.js code

### ISSUE THREAD

**Issue by mabasic** [laravelista/comments#1]
Use ES6 and webpack

**Comment by aqiltariq** [comment]
this is my comment.php in config folder
![image](https://cloud.githubusercontent.com/assets/8025359/21066096/78eb58ee-be85-11e6-9e28-a88d65ba9b88.png)
i m using it here in my model
![image](https://cloud.githubusercontent.com/assets/8025359/21066105/94d12ae8-be85-11e6-9bdc-1fd4bf393a2c.png)
my public folder 
![image](https://cloud.githubusercontent.com/assets/8025359/21066123/af178c76-be85-11e6-8bcf-0dcc2270d268.png)
 i m using it here in blade file 
![image](https://cloud.githubusercontent.com/assets/8025359/21066146/c9059e3e-be85-11e6-9a41-d43bc3d9e19f.png)
but this error is coming can u please help me 
![image](https://cloud.githubusercontent.com/assets/8025359/21066173/f075eb54-be85-11e6-875c-4a732eb96a03.png)
which is of react.js. I do not know react.js can you please help me to run this package

**Comment by mabasic** [comment]
Did you add `use Laravelista\Comments\Comments\Traits\Comments;` to your `App\User` model?

**Comment by aqiltariq** [comment]
yes sir u can see in the model pic
https://cloud.githubusercontent.com/assets/8025359/21066105/94d12ae8-be85-11e6-9bdc-1fd4bf393a2c.png

**Comment by mabasic** [comment]
In the pic I can see that you have added `use Comments` to the `App\Post` model, not `App\User` model. Can you check that you have `use Comments` in your User model and your Post model?

**Comment by aqiltariq** [comment]
Sir my comment.php is this 
![image](https://cloud.githubusercontent.com/assets/8025359/21066866/cd5af00c-be89-11e6-836e-5fc3c2a069f1.png)
my auth.php is this 
![image](https://cloud.githubusercontent.com/assets/8025359/21066878/df1923b8-be89-11e6-8639-3283e8fe660f.png)
my admin.php is this 
![image](https://cloud.githubusercontent.com/assets/8025359/21066889/edac0792-be89-11e6-9343-f6eef713c02b.png)
Still getting same error 
![image](https://cloud.githubusercontent.com/assets/8025359/21066911/096c766a-be8a-11e6-978f-7fc4317d2ee1.png)

**Comment by aqiltariq** [comment]
Sir can you please let me know that i have to add  anything related to react.js  file

**Comment by aqiltariq** [comment]
@mabasic is there anything related to react,js thing to be installed in my project?

**Comment by mabasic** [comment]
There is nothing to change related to react.js. Can you click on this marked in the image 
![096c766a-be8a-11e6-978f-7fc4317d2ee1_ink_li](https://cloud.githubusercontent.com/assets/1839930/21067256/4832c6e4-be6a-11e6-9784-42a0b97326b2.jpg)

and let me know what is says

**Comment by aqiltariq** [comment]
When i click on this marked by you
![image](https://cloud.githubusercontent.com/assets/8025359/21067396/cabd1c0a-be8c-11e6-942e-aff7387f1669.png)
i got this error
![image](https://cloud.githubusercontent.com/assets/8025359/21067414/e6d5a33a-be8c-11e6-98a8-0724c4de037a.png)

**Comment by mabasic** [comment]
Oh, I see. Which version of PHP are you using? This package works with version >= 7.0

**Comment by aqiltariq** [comment]
i am using php 5.5.4

**Comment by mabasic** [comment]
That is why this package is not working for you. I will later add a dependency in composer.json to require minimum PHP 7.0.

If you update to version 7.0 it will work.

**Comment by aqiltariq** [comment]
Can you please add this thing in documentation or in read.md as it is new project and very simple to use

**Comment by mabasic** [comment]
You can follow this lesson to update your PHP installation on Windows [Prepare for modern PHP applications](https://laravelista.com/series/laravel-on-windows/part/1)

**Comment by aqiltariq** [comment]
I will check nd inform you

**Comment by mabasic** [comment]
Ok, I will.

**Comment by aqiltariq** [comment]
Sir there is csrf toke mismatch error so do we to comment out this 
![image](https://cloud.githubusercontent.com/assets/8025359/21068238/91745bba-be92-11e6-8eae-f045b4465149.png)
its now working when we comment the middleware

**Comment by mabasic** [comment]
You need to add this to `app/Http/Middleware/VerifyCsrfToken.php` [see here](https://github.com/laravel/laravel/blob/master/app/Http/Middleware/VerifyCsrfToken.php):

```
protected $except = [
    'api/*'
];
```

I will add this to the readme.

**Comment by aqiltariq** [comment]
is there a facility of this thing in this plugin
hide old comments i.e sow recent comnents
![image](https://cloud.githubusercontent.com/assets/8025359/21072770/668c8096-beef-11e6-953e-06b0b34ae75b.png)

**Comment by mabasic** [comment]
You mean this "View old comments" button ?

**Comment by aqiltariq** [comment]
yes

**Comment by mabasic** [comment]
No, that does not come with this package. It is a simple Bootstrap [collapse component](http://getbootstrap.com/javascript/#collapse) in which I display "old" comments from when disqus was installed on this site.

You can use the collapse from bootstrap to display comments inside it, so that the user has to first click on the button "view comments" and then display the comments-react view inside it.

**Comment by mabasic** [comment]
Solved this issue with release `1.1.0` https://github.com/laravelista/comments/releases/tag/1.1.0
