### ISSUE TITLE
Multiple pages or just one?

### ISSUE THREAD

**Issue by Ande1232** [laravelista/comments#10]
Hi! Honestly I did not understand one thing, Can it be used on multiple pages or just one?
How do you know which article is that comment?

**Comment by mabasic** [comment]
Hi, I see that you have closed the issue before I got the time to respond. Did you find the answer in the documentation? 

You pass the id and model class to each instance of the package. There can only be one instance of the comment package on a sinhle page. This will change in the future. Currently you can have a singlr comment section on each page.

**Comment by mabasic** [comment]
See https://github.com/laravelista/comments/issues/5 for similar issur

**Comment by Ande1232** [comment]
Hello! Thanks a lot for the answer, I had found the answer in the documentation. Unfortunately, however, I have the same problem as ticket #6
