### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by dgillier** [laravelista/comments#101]
Hello, 

What do you think is the best way to add translation to the various msg, looks like all msg are in the view (but located in the vendor section).

Sorry to ask that, I'm a Laravel newbie...

Thanks for your help,
Denis

**Comment by mabasic** [comment]
Currently, you would have to publish the views (see readme), set translation plaxehokders and write the translations in your language files.

I am planning on adding translations directly to the package in the future.

**Comment by dgillier** [comment]
Great thanks you !
