### ISSUE TITLE
Exception: Class name must be a valid object or a string

### ISSUE THREAD

**Issue by helix4d** [laravelista/comments#103]
Project on Laravel Framework 6.18.20
install laravelista/comments and configure as in manual: magration, config, viewes
migrate successful: created table "comments"
added traits in model User and Post
in view post.blade.php inserted @comments(['model' => $post])
result: Facade\Ignition\Exceptions\ViewException
Class name must be a valid object or a string (View: /home/vagrant/code/public/ezoLinks/resources/views/vendor/comments/components/comments.blade.php)
Stack trace: https://flareapp.io/share/omw3zWmE#F60

**Comment by mabasic** [comment]
This could be a Laravel 6 edge case. 

Can you do run this from tinker in your app and paste the output here:

    config('comments.model');

It should return `\Laravelista\Comments\Comment::class`. If it does not then it has something to do with the config.

**Comment by helix4d** [comment]
thanks, you're right, output of command is null:
```
Psy Shell v0.10.4 (PHP 7.4.4 — cli) by Justin Hileman
>>> config('comments.model');
=> nul
```l
but the configuration file is in the folder _config\comments.php_ and there is a line in it
'model' => \Laravelista\Comments\Comment::class,

I tried to clean:
php artisan route:clear
php artisan optimize
php artisan cache:clear
php artisan view:clear
php artisan clear-compiled
composer dump-autoload

after these operations comments earned!
