### ISSUE TITLE
how its work if im using multiple login?

### ISSUE THREAD

**Issue by subhanassiddik** [laravelista/comments#104]
i have login user, admin, company.then have the separate models.if I'm login user its work.but if I'm login admin or company.I got massage I have to log in on the comment

**Comment by mabasic** [comment]
Only one user model is supported.

**Comment by subhanassiddik** [comment]
I've been added a commenter trait to all my user models. which works only on the user model.

**Comment by mabasic** [comment]
It should work on whatever model is authenticated. If you can pass "auth" in your application then this package will work.

**Comment by subhanassiddik** [comment]
thanks a lot
