### ISSUE TITLE
Reply to Self?

### ISSUE THREAD

**Issue by preimpression** [laravelista/comments#106]
How might I allow users to reply to themselves?

For instance, in my website I want to allow users to store information in their comments if they so desire, so that they can link to specific comments to share with other users. Just requiring them to edit the comment wouldn't be effective.

**Comment:** "Resources"
- **Reply:** "Resource one: [link]"
- **Reply:** "Resource two: [link]"

(On another note, permalinking individual comments should also be added)

**Comment by preimpression** [comment]
(Title changed because I thought I had figured out how to allow replying to self and wanted to recycle the issue, but then realized I hadn't actually fixed anything.)

**Comment by mabasic** [comment]
You could change the guard for comments reply.

**Comment by preimpression** [comment]
We got it to work - thanks! 

[and gotcha, did so!: #110 ]

**Comment by hondaman900** [comment]
Thanks Ne-wt, I reversed my changes and tried that, but no difference to the indenting. Went back to my markup hack for now.
