### ISSUE TITLE
Use blade for displaying purposes instead of react

### ISSUE THREAD

**Issue by billyrud** [laravelista/comments#11]
While the software was extremely easy to install and start using, it has several downfalls that I believe can be fixed by using blade for displaying. 

For example, users may have different timezone settings and as it's currently not possible to apply those settings when displaying the times. Another thing that I would like to do is remove the icon that is displayed next to the posts but again.

**Comment by mabasic** [comment]
I agree with you. I too have seen the downfalls and I also think that by using Blade I can fix those downfalls. When I get the time I will address the issues.

**Comment by mabasic** [comment]
Fixed in version [2.0.0](https://github.com/laravelista/comments/releases/tag/2.0.0)
