### ISSUE TITLE
How can i use Cache to store comments?

### ISSUE THREAD

**Issue by salimedia** [laravelista/comments#111]
Hi
After using this package, **How can i use Laravel Cache to store comments?** like that:

```
$comments = Cache::rememberForever("comments", function () {
       return CommentResource::collection(Comment::all()->load('user','post'));
});
```

because in blade we use just this code: `@comments(['model' => $post,'approved' => true])`

Thank you very much

**Comment by mabasic** [comment]
Comments for the model are grabbed from model `comments()` relationship. You could on your controller method where you  obtain the model, cache `$post->comments` for some reason. Don't know what is the use case for this, but it should be doable.
