### ISSUE TITLE
Laravel 8 Support

### ISSUE THREAD

**Issue by prof-usman** [laravelista/comments#115]
I'm trying to update my Laravel version to 8 but this package giving me the error

**Comment by mabasic** [comment]
I haven't updated it for Laravel 8 yet 😁

**Comment by prof-usman** [comment]
Please ping once you are done
Thank you

**Comment by prof-usman** [comment]
Please add Laravel 8 Support.
This is the only package which is disallowing me to upgrade to Laravel 8.

**Comment by mabasic** [comment]
I am currently very busy, so I won't be able to do anything about this for at least one month. 
You can wait for me or you could send a PR.

**Comment by jschlies** [comment]
Thanks Vendin

**Comment by prof-usman** [comment]
there is a PR available for Laravel 8 support

**Comment by rikvermeulen** [comment]
is it all ready to be approved for a new version thats supports laravel 8?

**Comment by prof-usman** [comment]
Hi @mabasic bro, it's now one month already, please upgrade it so that we can upgrade to Laravel 8.

**Comment by mabasic** [comment]
Very busy for at least two weeks. Once that is over I will dedicate time to update my open source projects. I don't want to do something in a rush

**Comment by usman-topdot** [comment]
thank you for the explanation, can you please specify how to tell composer to use my composer file?
can  you please write a little example code?

**Comment by mabasic** [comment]
A quick search on the Internet resulted in these results:

https://webtips.krajee.com/using-forked-version-of-packages-with-composer/
https://matthewsetter.com/series/tooling/composer/forked-repositories/

Taken from the website:

> Have you ever submitted a patch to a repository which your application relies on, but, because that patch is vital to the uptime of your application, you can’t wait for it to be reviewed and merged into the next release?
>
> In times like these, it’s fair to want them to move faster than they normally would, so that you don’t have to wait for the normal review, merge, and release cycles.
>
> However, you’re but one of many users of a library. And they’re not there solely to service our needs. Given that, just because you submit a patch doesn’t mean that they have to drop everything and merge it for us — assuming that it passes review.
>
> But, you may urgently need the patch to be applied and released. So, what do you do? In times like these, you can use Composer’s ability to use custom repositories, specifically a fork which you create and patch.
>
> If this sounds appealing to you — because perhaps you’re in this very situation right now — let’s now step through the process of modifying your composer.json configuration so that you can use one.

**Comment by ereznet** [comment]
Please add Laravel 8 Support :)

**Comment by mabasic** [comment]
Added support for Laravel 8 in version 4.0.0. Requires PHP 7.4
