### ISSUE TITLE
Soft-delete config option, does not work

### ISSUE THREAD

**Issue by patourasalexandros** [laravelista/comments#116]
Hello. 

Even if i put:
    'soft_deletes' => false
it does not take effect. I have the classic error "Column deleted_at not found".
The problem is, that soft delete columns added to the original migration, and not to an additional one. 
Do i missing something?

**Comment by mabasic** [comment]
See the readme for troubleshooting. I've added a chapter which explains how to add missing columns with migrations.

**Comment by patourasalexandros** [comment]
I am missing indeed. I did not see it, due to panic. Thanks and sorry.
