### ISSUE TITLE
Add limit to reply comments

### ISSUE THREAD

**Issue by RiyanAmanda** [laravelista/comments#118]
I dont know how to solve this, pls help.
![comment](https://user-images.githubusercontent.com/60539506/93872743-cc6de880-fcfa-11ea-8943-5b917417873e.png)

**Comment by preimpression** [comment]
What's exactly going wrong? 
Are these not supposed to show as replies? You may be missing a `</div>`
Indenting too wide? That's just caused by the fact that the package uses bootstrap media object nesting.

**Comment by mabasic** [comment]
I think that he wants to limit the depth of replies/comments. I think that it should be possible by modifying the reply permission to detect how deep the current comment it.

**Comment by RiyanAmanda** [comment]
> I think that he wants to limit the depth of replies/comments. I think that it should be possible by modifying the reply permission to detect how deep the current comment it.

Yes, that's what i want. I think if every comment has no limit of depth replies, I don't imagine how wide the comment section going to be.

**Comment by mabasic** [comment]
Implemented. See [here](https://github.com/laravelista/comments#configure-maximum-indentation-level) for instructions. You must update to the latest version to use this feature `4.2.0`.
