### ISSUE TITLE
Align comments 

### ISSUE THREAD

**Issue by vitorhenriquemaia** [laravelista/comments#122]
Hey! Thanks for the package!

I just got a question. How can I align reply above each other?`
![github comments](https://user-images.githubusercontent.com/51383706/96715155-8ba8d400-1379-11eb-8587-8f389531c56c.png)
`

**Comment by mabasic** [comment]
Thank you.

It is possible, but you will have to publish and configure the views to match your desired outcome.

See this chapter in the readme: https://github.com/laravelista/comments#publish-views-customization
