### ISSUE TITLE
Modal update problem

### ISSUE THREAD

**Issue by djordje47** [laravelista/comments#127]
Hi, loved ur package. 

There is one small problem that needs a fix. 

Change cancel and update label on update modal. Because I installed it today when u click on update, the modal is dismissed and when u click on cancel comment is updated. 

Cheers!

**Comment by mabasic** [comment]
I must have forgotten to change the actions, only changed text lol

Will need to confirm this and make changes. Thank you for reporting.

**Comment by djordje47** [comment]
Yeah just change labels, and it's done! :smile: 

You are welcome!

**Comment by mabasic** [comment]
Fixed in 4.4.1.

The order of buttons on modals was meant to be [cancel, update] and [cancel, reply]. In a previous commit I've changed the labels instead of changing the order of the buttons. xD
