### ISSUE TITLE
Your requirements could not be resolved to an installable set of packages.

### ISSUE THREAD

**Issue by Spot-up** [laravelista/comments#129]
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - laravelista/comments[3.6.0, ..., 3.6.1] require illuminate/database ^5.6|^6.0|^7.0 -> found illuminate/database[v5.6.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev] but it conflicts with another require.
    - Root composer.json requires laravelista/comments ^3.6 -> satisfiable by laravelista/comments[3.6.0, 3.6.1].

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

**Comment by kuddus137** [comment]
I am also having this issue, please provide us a solution

**Comment by mabasic** [comment]
@kuddus137 @Spot-up The latest version of this package is `4.4.1` and it works on Laravel 8. What are your version of Laravel and PHP and what are you trying to do?

**Comment by kuddus137** [comment]
I have laravel version 7. how can I install it?

**Comment by mabasic** [comment]
Can you send me the full output you get while installing?

**Comment by Spot-up** [comment]
My php version 7.3.21, Laravel version 8.7.1

**Comment by mabasic** [comment]
@Spot-up The latest version of this package which supports Laravel 8 requires PHP 7.4 version. You should update your PHP version and it should work. Let me know how it goes.

**Comment by Spot-up** [comment]
Thank You
 
--
С уважением Cемен Потапов
