### ISSUE TITLE
Comment view

### ISSUE THREAD

**Issue by tareqdokhan** [laravelista/comments#13]
How to Have a View i copy it but nothing happend

**Comment by tareqdokhan** [comment]
i really need this plugin ,, can any body help me

**Comment by mabasic** [comment]
Sorry dude, I'm currently busy with other things. Will come back to this once able.

**Comment by mabasic** [comment]
Fixed in version [2.0.0](https://github.com/laravelista/comments/releases/tag/2.0.0)
