### ISSUE TITLE
Possible without bootstrap?

### ISSUE THREAD

**Issue by eduardonwa** [laravelista/comments#132]
I dont like using bootstrap but if required im usually okay with it (not my first choice), struggling to modify all of the classes for my personal blog, I wonder if you could hopefully release a version that doesnt use it. I do understand millions of websites use it, non designers. In other topics its a wonderful component!

**Comment by mabasic** [comment]
Thank you. You can publish the views and modify them however you want (html, css). You can even use the package API endpoints (with a few tweaks) to use this package with React, Vue or other JS implementation.
