### ISSUE TITLE
commentable id is empty

### ISSUE THREAD

**Issue by mahdi4k** [laravelista/comments#135]
when im want submit a commnet , commentable id is empty and comment not submited what is wrong?

**Comment by mabasic** [comment]
I don't know. View the error log for errors, inspect the request response for errors. Read the documentation again in case you missed something.

Let me know if you have managed to solve your issue.

**Comment by mahdi4k** [comment]
sorry my bad .is for route model binding typography wrong. actually empty data passing to comment page.
