### ISSUE TITLE
moveing package from local to sharing host

### ISSUE THREAD

**Issue by mahdi4k** [laravelista/comments#136]
hi im using sharing host and im Inaccessibility to command line for composer . all files is copied to host like vendor folde and trait is added. but is still not working. what i do?

**Comment by mabasic** [comment]
This has nothing to do with this package, so I will be closing this issue.

A few things to verify and try:

- is only this package not working or your entire app
- do not copy only the vendor files but copy the entire project

**Comment by mahdi4k** [comment]
im copy the entire project .only thing is changed in host directory vendor/autoload.php and bootstrap/app.php .other package working well

**Comment by mabasic** [comment]
Can't help you here. There is something you have missed which has nothing to do with this package.

Do you get any errors. Did you  check the logs

**Comment by PierreMatos** [comment]
I guess I have the same problem. Its working fine in the localhost but in the server It just prints  (['model' => $model]) in the page
i'm using Laravel 8, I've also copied the whole project to the server and cleared all caches

**Comment by mahdi4k** [comment]
> I guess I have the same problem. Its working fine in the localhost but in the server It just prints (['model' => $model]) in the page
> i'm using Laravel 8, I've also copied the whole project to the server and cleared all caches

remove all cache files in storage folder

**Comment by Nikunj1696** [comment]
![image](https://user-images.githubusercontent.com/31561407/108755847-c57b2880-756d-11eb-8a1f-c12c20d14684.png)

i have same issue 
i also tried to clear caches

**Comment by mabasic** [comment]
Have you tried with `{!! !!}` instead of `{{ }}`?

**Comment by mabasic** [comment]
It looks like the service provider is not loaded automatically. Try adding it manually following the instructions in the readme.

**Comment by Nikunj1696** [comment]
everything is up to date still not solved...

**Comment by mabasic** [comment]
It could be up to date, but laravel needs to autoload the package for it to work (this requires command line access) or you need to manually add this.

If the package works for you locally, but stops working on production environment, then you need to deduce what are the differences because most likely it is not because of this package.
