### ISSUE TITLE
Your requirements could not be resolved to an installable set of packages.

### ISSUE THREAD

**Issue by shubhamchugh** [laravelista/comments#138]
Problem 1
    - laravelista/comments[3.6.0, ..., 3.6.1] require illuminate/database ^5.6|^6.0|^7.0 -> found illuminate/database[v5.6.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev] but it conflicts with another require.
    - Root composer.json requires laravelista/comments ^3.6 -> satisfiable by laravelista/comments[3.6.0, 3.6.1].

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

when i am tring to install this package then, getting this error.

Stack:
Laravel: 8 with jetstream
database: mysql
environment: xampp on mac localhost

**Comment by mabasic** [comment]
The requirements for the latest version of this package (`4.4.1`) that supports Laravel 8 are:

- PHP 7.4
