### ISSUE TITLE
Can't comment even though user is logged in.

### ISSUE THREAD

**Issue by AlanH97** [laravelista/comments#14]
I reproduced all the steps provided in the installation, included the comments in my designated Model, being simple news articles, but I can't seem to comment anything even though a user is logged in, when I press on the login link (as a logged in user) in "You must **login** to post a comment." It redirects me to a /home route that doesn't exist in my project, otherwise, if a user isn't logged in, the link redirects me to my login page. 
Any help would be appreciated!

**Comment by mabasic** [comment]
Fixed in version [2.0.0](https://github.com/laravelista/comments/releases/tag/2.0.0)
