### ISSUE TITLE
Get the comment's post

### ISSUE THREAD

**Issue by eduardonwa** [laravelista/comments#141]
I dont think this is explained in the documentation (maybe it doesn't need to) but what im trying to do is, get a post from a list of comments. I been trying to reference the "commentable_type" column but it only displays the Post model path as a string ("App\Models\Post"), but I want to jump straight into the post in case there is a question for me, how would I do this?

**Comment by mabasic** [comment]
```
$comment->commentable
```

Will return the model you want.

It is in the Laravel documentation under Polymorphic relationships.
