### ISSUE TITLE
syntax error, unexpected 'SpamResponder' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST) 

### ISSUE THREAD

**Issue by eduardonwa** [laravelista/comments#142]
Recently I updated composer and with this came a newer version of php, I downgraded both but now im not so sure which version was the right one, it could be that this mightv'e affected one of my favorite packages.

Im running Composer version 1.10.17, and PHP 7.4.13. 

Which PHP or Composer version is required? The package was running nicely before, thanks. 

https://flareapp.io/share/lm23lXqP

Ive attached the error log just in case.

**Comment by mabasic** [comment]
Are you sure that you are running PHP 7.4?

Composer version does not matter. The package should run just fine with PHP 7.4 and Laravel 8

**Comment by eduardonwa** [comment]
To be honest I have been struggling with that, I just don't know how! Im sure it's one of those things but wouldn't hurt to ask :)

**Comment by mabasic** [comment]
Don't know where you are hosting your website, but check your `php-cli` version, and if you are using nginx `php-fpm` version.
