### ISSUE TITLE
Comment counts

### ISSUE THREAD

**Issue by Topnetworks** [laravelista/comments#149]
Is there a way to use say $post->comments->count() but not have it count the "child comments/replies" only the main comments?

Thanks,
Les

**Comment by mabasic** [comment]
This should do:

```
$post->comments->where('child_id', '')->count();
```

or

```
$post->approvedComments->where('child_id', '')->count();
```

**Comment by Topnetworks** [comment]
wow so simple, this is why i love this package, Thanks heaps

**Comment by Topnetworks** [comment]
Might be a stupid question but is there an easy way to get the users name (username in my case) as well? for example i used the following on a show all posts page so shows comment count for each post but i also need next to use "created_at" and Username of the comment.. Thanks champion

**Comment by mabasic** [comment]
Instead of sending you the answer I am sending you a place where to look for stuff like that:

https://github.com/laravelista/comments/blob/master/src/Comment.php#L57

**Comment by Topnetworks** [comment]
Sorry, still learning Laravel and how models and such work.. im not the most smartest cookie in the gorup lol

**Comment by mabasic** [comment]
You'll get there. Just keep trying <3

**Comment by Topnetworks** [comment]
Thanks bud!
