### ISSUE TITLE
DB migration issue

### ISSUE THREAD

**Issue by thekillerisme** [laravelista/comments#15]
Hi,
thanks for the package.

I believe I found an issue with the migration. The `child_id` foreign key has a different column type from the `id` column. So, when you run `php artisan migrate`, an error occurs:
`SQLSTATE[HY000]: General error: 1215 Cannot add foreign key constraint`

More info:
`foreign key (`child_id`) references `comments` (`id`) on delete cascade:
Cannot find an index in the referenced table where the
referenced columns appear as the first columns, or column types
in the table and the referenced table do not match for constraint.
Note that the internal storage type of ENUM and SET changed in
tables created with >= InnoDB-4.1.12, and such columns in old tables
cannot be referenced by such columns in new tables.
Please refer to http://dev.mysql.com/doc/refman/5.7/en/innodb-foreign-key-constraints.html for correct foreign key definition.`

Changing the column type of the child_id column from BIGINT to INT fixes the issue:
`$table->unsignedInteger('child_id')->nullable();`

**Comment by mabasic** [comment]
I will have to take a closer look at this one.

**Comment by jeverington** [comment]
Having the same issue here. Running on MariaDB

**Comment by walidbagh** [comment]
I fixed this issue by changing:

`$table->increments('id'); `
to 
`$table->bigIncrements('id'); `

as 'child_id' column is BigInteger.

and also specified `$table->engine = 'InnoDB';` in the migration to make sure it works on production server.

**Comment by mabasic** [comment]
@walidbagh I like this better, but I need to find out why this does not work for you, but works for me. Maybe it's the mysql version... 

Going to fiddle with it in a couple of hours and release a fix.

This should no

**Comment by mabasic** [comment]
Fixed with version [`2.0.1`](https://github.com/laravelista/comments/releases/tag/2.0.1)
