### ISSUE TITLE
I cant install package with my composer 

### ISSUE THREAD

**Issue by BorisGerat** [laravelista/comments#152]
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - laravelista/comments[1.1.0, ..., 1.1.2] require illuminate/support ^5.2 -> found illuminate/support[v5.2.0, ..., 5.8.x-dev] but these were not loaded, likely because it conflicts with another require.
    - Root composer.json requires laravelista/comments ^1.1 -> satisfiable by laravelista/comments[1.1.0, 1.1.1, 1.1.2].

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

**Comment by mabasic** [comment]
The latest version supports php7.4 and laravel 8. You should upgrade your installation to install the latest version, or you could use an older version of it works for you.
