### ISSUE TITLE
unable to use two different gurd for comment

### ISSUE THREAD

**Issue by sarojbrt1** [laravelista/comments#153]
unable to use two different gurd for comment , when i try to comment with diffrent it redirect to login page..

**Comment by mabasic** [comment]
Could you explain more on what you are trying to do?

**Comment by sarojbrt1** [comment]
i have two different user login guard..  and two different user  should be able to comment in same post..  i am able to comment from user side but when i try to comment by branch it redirect to login page... any solution??

**Comment by sarojbrt1** [comment]
@mabasic waiting for your response..

**Comment by mabasic** [comment]
It all depends on your application and how you handle two different user models logging in. This package supports different user models being the Commenter, If you can pass the default (Auth::check) with both users then all should be fine. This package grabs the user from `$request->user()`. Check the package views if they need changing and/or the CommentController.
