### ISSUE TITLE
Making events for new comment

### ISSUE THREAD

**Issue by eduardonwa** [laravelista/comments#154]
If I want to get an email notification whenever a post gets a new comment should I include the Listener in the vendors/laravelista/comments/ folder, or could I make it inside the App folder and create the listener within the app folder? If you can in fact create the listener right in the app, how should I ask for the CommentCreated.php class event?

**Comment by eduardonwa** [comment]
Why was the Dispatch trait wasn't included in the CreatedComment? Can I use it? Wouldn't want to break anything.

**Comment by mabasic** [comment]
See my comment in #137.

**Comment by eduardonwa** [comment]
Like this: 

```
    protected $listen = [
        Registered::class => [
            SendEmailVerificationNotification::class,
        ],
        \Laravelista\Comments\Events\CommentCreated::class => [
            SendEmailNewComment::class,
        ],
    ];
    ```

**Comment by mabasic** [comment]
That should do it.
