### ISSUE TITLE
Comment dont go to database

### ISSUE THREAD

**Issue by Xinaga** [laravelista/comments#156]
"The commentable id field is required." When I go to Database dont show any data. Im Using sqlite, can this be the problem?

**Comment by mabasic** [comment]
I'm using sqlite for testing too, so it isn't because of it. 

You are probably not passing the model correctly to the comment component:

```
@comments(['model' => $book])
```

You would get that error if `$model->getKey()` returns null for some reason.

**Comment by Xinaga** [comment]
This model needs a ID?

**Comment by mabasic** [comment]
Ofcourse. The model should be persisted in database.

**Comment by Xinaga** [comment]
Last question, Can I remove the photo?

**Comment by mabasic** [comment]
Sure thing. Publish the views (see readme for this) and remove the photo there.

**Comment by Xinaga** [comment]
Thanks Mario!

**Comment by mabasic** [comment]
ZZZZZZZZZ '

lp*;,,,0,3071
