### ISSUE TITLE
Error running composer require laravelista/comments on Laravel 8.12

### ISSUE THREAD

**Issue by BarataJhones** [laravelista/comments#157]
Problem 1
    - laravelista/comments[1.1.0, ..., 1.1.2] require illuminate/support ^5.2 -> found illuminate/support[v5.2.0, ..., 5.8.x-dev] but these were not loaded, likely because it conflicts with another require.
    - Root composer.json requires laravelista/comments ^1.1 -> satisfiable by laravelista/comments[1.1.0, 1.1.1, 1.1.2].

**Comment by mabasic** [comment]
PHP version?

**Comment by BarataJhones** [comment]
8

**Comment by mabasic** [comment]
Added support for PHP 8 in version `4.5.0` (just now). Try again.
