### ISSUE TITLE
Impossible to install via composer

### ISSUE THREAD

**Issue by ligoo** [laravelista/comments#16]
Hello,

seems to be a great package. Unfortunatelly when I try to install it it shows me this:

```
  - Installing laravelista/comments (2.0.1): Loading from cache
Writing lock file
Generating autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover

In Facade.php line 221:
  Call to undefined method Illuminate\View\Compilers\BladeCompiler::component() 
Script @php artisan package:discover handling the post-autoload-dump event returned with error code 1

Installation failed, reverting ./composer.json to its original content.
```

Any idea how to fix this ? I'm using Laravel 5.5.40

**Comment by mabasic** [comment]
Sorry about that. The package currently only works on Laravel 5.6. because of that blade component. Will try to work around that in future versions

**Comment by ligoo** [comment]
Thanks for the reply. I've updated to 5.6, so it's working like a charm now. Keep it up! Love your work.

**Comment by mabasic** [comment]
Thank you very much.
