### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by Tzerkee** [laravelista/comments#160]
I want install this package but it does not support Laravel 8

**Comment by mabasic** [comment]
Can you paste the error that you are getting. The package should work on Laravel 8

**Comment by Tzerkee** [comment]
Using version ^3.6 for laravelista/comments

./composer.json has been updated
Running composer update laravelista/comments
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - laravelista/comments[3.6.0, ..., 3.6.1] require illuminate/database ^5.6|^6.0|^7.0 -> found illuminate/database[v5.6.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev] but these were not loaded, likely because it conflicts with another require.
    - Root composer.json requires laravelista/comments ^3.6 -> satisfiable by laravelista/comments[3.6.0, 3.6.1].


Installation failed, reverting ./composer.json and ./composer.lock to their original content.

**Comment by mabasic** [comment]
laravelista/comments version 4.0.0 and above supports Laravel 8. Try using `composer require laravelista/comments` or update the version constraint to `^4.0` in `composer.json`.
