### ISSUE TITLE
Comment enable or disable by post's owner

### ISSUE THREAD

**Issue by Parshant0171** [laravelista/comments#162]
First of all thanks for the great package,
I have a query that if I have to make a customization that the other users can only comment if the comment system is enable by the owner of the post or other users can only reply to the comment created by the owner of the post.

**Comment by mabasic** [comment]
Thank you for the kind words ❤️ 

You could do this by adding a field on your post model `comments on/off` or something like that. Then depending on that you could show or hide the comments component. That is out of the scope for this package.

Permissions can be customized, see [here](https://github.com/laravelista/comments/blob/master/config/comments.php#L12-L21). Let me know if you have more questions.
