### ISSUE TITLE
Installation Problem

### ISSUE THREAD

**Issue by elsayedabdelnaby** [laravelista/comments#169]
@mabasic 
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires laravelista/comments ^4.5 -> satisfiable by laravelista/comments[4.5.0].
    - laravelista/comments 4.5.0 requires illuminate/database ^8.0 -> found illuminate/database[v8.0.0, ..., 8.x-dev] but these were not loaded, likely because it conflicts with another require.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

**Comment by FathanAkram-app** [comment]
same here

**Comment by mabasic** [comment]
Can you post your Laravel and PHP versions?

**Comment by FathanAkram-app** [comment]
no i quit trying to solve this XD, i make a comment relation on my own, i dont use library

**Comment by elsayedabdelnaby** [comment]
@mabasic php7.4 and Laravel "laravel/framework": "^7.29",

**Comment by mabasic** [comment]
> @mabasic php7.4 and Laravel "laravel/framework": "^7.29",
> 

The latest version of this package `4.5.0` works with PHP 7.4 and PHP 8.0 and with Laravel 8.

Version `3.5.0` was the last version to support Laravel 7. I cannot recommend using this older version, but I would suggest that you upgrade to Laravel 8 instead.

**Comment by elsayedabdelnaby** [comment]
@mabasic Ok, Thanks
