### ISSUE TITLE
Different Documentation

### ISSUE THREAD

**Issue by dionajie** [laravelista/comments#18]
I just installed this package using composer. But when i continue to migrate the database, it showed that nothing to migrate. I'm using steps from this page. 
But when i open readme.md in vendor file, it's different. File structure is different too.
Seems like when im running composer require, it downloads ver.1xx

**Comment by mabasic** [comment]
Did you use composer require laravelista/comments?

Check your compose.json fike and manually update the version to latedlst and then do composer update.

Let me know if it works.

**Comment by dionajie** [comment]
it turns out that my version of php still 7.1.3 both in server and laravel. After i upgrade my php ver, it works! 
If you still under 7.2, composer will install ver 1.1.3 instead of 2.0.1

Thanks @mabasic!

**Comment by mabasic** [comment]
Thanks for the feedback.
