### ISSUE TITLE
XSS injection in parsedown (SafeMode disabled)

### ISSUE THREAD

**Issue by Ostap34JS** [laravelista/comments#22]
Hi.
https://github.com/laravelista/comments/blob/master/resources/views/_comment.blade.php#L1

I recommend use "Safe Mode".

https://github.com/erusev/parsedown#security

becouse now SafeMode disabled, and it have xss injection.

Maybe solution:

Change line number 2 in _comment.blade.php:

```
@php($markdown->setSafeMode(true))
```

Thanks...

**Comment by mabasic** [comment]
I see, thank you. Will implemented this in the next version.
