### ISSUE TITLE
If user's email is Gmail then no comments can be save

### ISSUE THREAD

**Issue by yoesoff** [laravelista/comments#23]
I have 4 users in my users table, those are:

- admin1@email.com

- admin2@email.com 

- mhyusuf@gmail.com

- fiqi@gmail.com

My issue is both fiqi@gmail.com and mhyusuf@gmail.com **cannot save the comment** while 2 others are working very well, any solution for this?

**Comment by yoesoff** [comment]
Hi, I just realized that the comments were saved to the comments's table but doesn't displayed, any solution?

**Comment by yoesoff** [comment]
My bad, I put commenter on post and commentable on user so it was confuse the code

**Comment by mabasic** [comment]
Glad that you got it working.
