### ISSUE TITLE
like on comments and replies

### ISSUE THREAD

**Issue by Naveedali1234** [laravelista/comments#24]
Hello Laravelista, 

I really appreciate your efforts for this package, i was just thinking if you can add the like feature on comments and replies. then this package would be more flexible and usable.

**Comment by mabasic** [comment]
It could be easily implemented with a table for likes and added functionality. If you want to send a PR I would be willing to work with you on this.

**Comment by mabasic** [comment]
Just to confirm, this feature will be implemented.

**Comment by mabasic** [comment]
Maybe a heart with a number of likes...

:heart: 3

and when there is only one like it should only display a :heart:

**Comment by mabasic** [comment]
I have decided not to include this in this package yet. I'll create a separate repo where I will show an implementation of this and put a link here
