### ISSUE TITLE
Guest commenting

### ISSUE THREAD

**Issue by mattrabe** [laravelista/comments#26]
I would like users to be able to leave a comment as a guest (without logging in) on my project. Is there any support or roadmap for this? If not, would you be open to a PR? I would think requiring a recaptcha a for guest comments would be sensible.

**Comment by mabasic** [comment]
This could be easily achieved. Sure thing, send me a PR and we will work on this.

**Comment by mabasic** [comment]
Just to confirm, this feature will be implemented.

**Comment by mattrabe** [comment]
I have not had a chance to work on a PR on this, and I'm pretty busy for the foreseeable future so I won't be able to get to it any time soon.

**Comment by mabasic** [comment]
No problem.

**Comment by mabasic** [comment]
This feature should be enabled by setting the `guest_commenting` configuration option to `true`.

I don't want to tie recaptcha into this package, maybe someone wants to implement a different thing for spam prevention. This will be left to the developer until I gather more feedback.

For now, once the guest commenting feature is enabled. A form for leaving a comment will be displayed along with an email field. Once entered, a "dummy" user will be created and associated  with the comment. In the future if a user registers into your application with that email (if you allow registration) you could easily connect him with his comments.

**Comment by mattrabe** [comment]
@mabasic link to a PR/commits?

**Comment by mabasic** [comment]
Just thinking about this out loud :)

**Comment by mabasic** [comment]
Maybe just to collect user information necessary for this package to work (email & name) without creating a dummy user. Store the information in the table.

If needed the developer can connect the comment to the user later by using the email address.

**Comment by mabasic** [comment]
Comment approval has been implemented #50 so turning this feature on could be manageable even without a spam prevention system.

**Comment by rocramer** [comment]
@mabasic Regarding spam protection: [Laravel Honeypot](https://github.com/spatie/laravel-honeypot) could be used. It is great because it is really easy to implement, the user do not have to fill out anything and the website owner has no problems with data privacy laws (especially in the EU) because no third party is involved. I think the package is a good starting point for securing forms. I can create a PR if wanted.
