### ISSUE TITLE
php version question

### ISSUE THREAD

**Issue by ionesculiviucristian** [laravelista/comments#28]
Why require php 7.2.* when the latest version of Laravel uses 7.1.*?

**Comment by mabasic** [comment]
Interesting question. I usually require the latest PHP version available at the moment. Do you need it to work on PHP 7.1?

**Comment by mabasic** [comment]
Ok, this release should make you happy [`2.0.2`](https://github.com/laravelista/comments/releases/tag/2.0.2).

I haven't tested this in a Laravel application yet, but It should work nicely on Laravel `5.6` and up.

**Comment by ionesculiviucristian** [comment]
Installing on Laravel 5.7 and php 7.1. Many thanks.
