### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by OAnouman** [laravelista/comments#30]
Hey !
Well done with this plugin. It's very useful.
I only got one thing to suggest : Add localization feature. I think it would be very appreciated and will make it even better.

**Comment by mabasic** [comment]
Hi, thank you.

You can publish the view files with: 

```
php artisan vendor:publish --provider="Laravelista\Comments\ServiceProvider" --tag=views
```

and then change the text and layout however you want.

In the next release I will be sure to implement localization out of the box
