### ISSUE TITLE
Override defined permission

### ISSUE THREAD

**Issue by macagoraga** [laravelista/comments#34]
How can I override defined permission like edit-comment, delete-comment, etc.
I try to add them in my AuthServiceProvider, but it not work.

**Comment by mabasic** [comment]
You could [opt out of package discovery](https://laravel.com/docs/5.7/packages#package-discovery) for this package and then write your own service provider by copying the [package service provider](https://github.com/laravelista/comments/blob/master/src/ServiceProvider.php) and then registering that in your `config/app.php`.

I think that that should work.

**Comment by macagoraga** [comment]
I think a similar solution as well, but maybe using a Policy class and then define in config which one to use, will allow to override without duplicate code of ServiceProvider.

I make a pull request, if you want to check into.

1) I add new CommentPolicy.php

2) I updated ServiceProvider.php how is defined the permission, using:

```php

        // Define permission defined in config
        $permissions = config('comments.permissions', [
            'create-comment' => 'Laravelista\Comments\CommentPolicy@create',
            'delete-comment' => 'Laravelista\Comments\CommentPolicy@delete',
            'edit-comment' => 'Laravelista\Comments\CommentPolicy@update',
            'reply-to-comment' => 'Laravelista\Comments\CommentPolicy@reply',
        ]);
        foreach($permissions as $permission => $policy) {
            Gate::define($permission, $policy);
        }

```

3) In config I added below which can be override by application:

```php



    'permissions' => [
        'create-comment' => 'Laravelista\Comments\CommentPolicy@create',
        'delete-comment' => 'Laravelista\Comments\CommentPolicy@delete',
        'edit-comment' => 'Laravelista\Comments\CommentPolicy@update',
        'reply-to-comment' => 'Laravelista\Comments\CommentPolicy@reply',
    ]

```

4) I also added new permission for create-comment, which per default is true. So in controller `store` method I add   `$this->authorize('create-comment', Comment::class);`


The rest is untouched so it should not break anything else.

**Comment by mabasic** [comment]
Wow, this is great stuff. I like the PRs and will merge as soon as we resolve the issues that I commented upon.
