### ISSUE TITLE
Performance on replies

### ISSUE THREAD

**Issue by ionesculiviucristian** [laravelista/comments#39]
Hi. Is there a out of the box way to optimize performance for more levels of replies? In your views there are on the fly queries being executed. 

Would have been nice to have a library like https://github.com/lazychaser/laravel-nestedset used for this purpose.

**Comment by mabasic** [comment]
Hi,

currently there are no optimizations. I will have to find time to test the performance and check the queries when there are a lot of comment involved. What I usually do is eager load the comment with `with('comments')`, but I think that the issue you are saying is with a lot of child comment.

**Comment by guoxiangke** [comment]
![image](https://user-images.githubusercontent.com/1160703/55262982-9b9a2800-52aa-11e9-895b-d410a521c679.png)
I add lines 7-8 to advoid some N+1 query.
But still has one: 
![image](https://user-images.githubusercontent.com/1160703/55263058-d308d480-52aa-11e9-862d-8fbf54c691c9.png)

I try add 
        <?php $comment->load('user');?>
 & add user belongTo comment Model but not work.
![image](https://user-images.githubusercontent.com/1160703/55263136-ffbcec00-52aa-11e9-8535-ef75c3fc6af2.png)

**Comment by mabasic** [comment]
I have just spent two hours trying to eager load deeply nested relationships called for children of children of children...

This does not work.

I have read the entire readme for this package [lazychaser/laravel-nestedset](https://github.com/lazychaser/laravel-nestedset) and I still don't understand what is it for and how to use it.

**Comment by mabasic** [comment]
Holy shit! I have managed to solve this. Commit coming soon...
