### ISSUE TITLE
Change Image 

### ISSUE THREAD

**Issue by aqiltariq** [laravelista/comments#4]
The default image is showing with the comment.
I have image path of user profile in column name avatar in user table.
How can i set the image from that column

**Comment by aqiltariq** [comment]
@mabasic can you let  us know how to change the image? I have to do it urgent for some work as it is one of the best laravel comment plugin

**Comment by mabasic** [comment]
Hello, I have been thinking about this, but currently it is not possible.

User image is obtained from Gravatar based on the user email. In the future, I could implement a system that would allow setting the image from a column in the database.

Going to add it to the board.

**Comment by aqiltariq** [comment]
Thank You.
After this it will make the most effective laravel comment package.

**Comment by mabasic** [comment]
Fixed in version [2.0.0](https://github.com/laravelista/comments/releases/tag/2.0.0)

You can now publish the views and change them however you want. See the readme for more info.

**Comment by softtechnoes** [comment]
Hey ! We are not able to change profile picture of commenter... can you tell us how can we fixed it, Please !!!

**Comment by mabasic** [comment]
@softtechnoes 

[Use this to publish the views](https://github.com/laravelista/comments#publish-views-customization)

Then inside `resources/views/vendor/laravelista/comments` change [this line](https://github.com/laravelista/comments/blob/master/resources/views/_comment.blade.php#L9) to where you keep your image for the user.

**Comment by softtechnoes** [comment]
that line only showing the online avatar but I don't want that, I want my user's pictures stored in db

**Comment by mabasic** [comment]
Replace `src` attribute value with your own. For example: `src="{{ asset('images/' . $user->db_image) }}"`

**Comment by softtechnoes** [comment]
that will show same images for all comments

**Comment by mabasic** [comment]
My mistake, use `$comment->commenter->db_image` to get the `db_image` from user who posted the comment.

**Comment by softtechnoes** [comment]
Yeah!! now `$comment->commenter->db_image` working smoothly, thanks for giving me time :)
