### ISSUE TITLE
Where are the docs?

### ISSUE THREAD

**Issue by maidul98** [laravelista/comments#43]
I see some "how to install" on the main page, but is there no documentation beyond that? I am trying to make a rest api, so i  need routes to create and such. Also, when I install, I don't have a migration file for comments. Any ideas as to what's going on?

**Comment by mabasic** [comment]
Most likely it is not ready for Laravel 5.8. I haven't tested it yet. The documentation and a huge update is coming soon.

**Comment by mabasic** [comment]
What is your Laravel version btw? The migrations should work.

**Comment by mabasic** [comment]
I have just updated the readme with REST API chapter. That will help you to create an implementation
