### ISSUE TITLE
Does not display comments

### ISSUE THREAD

**Issue by TitoxDboss** [laravelista/comments#44]
I have just downloaded [laravelista/comments](https://github.com/laravelista/comments/issues/new).

I followed the instructions exactly, I think, when I open `localhost:8000/post/show/1`(because that is my specified view),it shows the details of the post and the comment text area.When I type into the comment textarea, and press submit,it reloads the page and **does NOTHING**.It doesn't insert the data into the `comment` table nor does it show the just typed comment nor does it even show any **error**.So at this point,I don't have a clue what is going wrong.

I know I am supposed to post some of my code,but I don't know which code to post,whether it  is the `routes`,the `blades` files,the `migrations`,the `db schema`,the `laravelista/comments` source etc and I can't just go ahead and post _**everything**_ or post some code that you won't even need.

So please,any code that you may like to view to help me out just kindly let me know and I will be happy to show you.

Thanks in advanced

**Comment by mabasic** [comment]
Better documentation coming soon.

**Comment by mabasic** [comment]
This is what I need:

- laravel version
- the blade view where you included this package
- controller which returns the above view file

**Comment by mabasic** [comment]
In this commit 70944dd39f670b1fe0de87e69251a8bfb50a5f20, I have enabled displaying errors for hidden fields. That should be enough to point you in the right direction. Wait for the next release for this to get included.
