### ISSUE TITLE
422 error when trying to comment?

### ISSUE THREAD

**Issue by agouticreative** [laravelista/comments#6]
Hi. I wanted to give your package a shot and implementation went smoothly until I tried to post a comment for the first time. 
It appears that three api calls happen, two of which are the same:

one is a GET of /api/v1/comments, returns a 422. this is the response: {"error":{"message":{"content_type":["The content type field is required."],"content_id":["The content id field is required."]},"status_code":422}} It doesn't seem to send the contents of window.Laravelista, which I have to imagine is what it wants to do.

Then a second one happens that seems marginally more successful. It is a GET of  http://www.airhub.dev/api/v1/comments?content_type=App%5CModels%5CExpense&content_id=19, which returns something like this: {"data":[],"meta":{"user":{"data":{"id":2,"name":"User Name","email":"xxxxxx@gmail.com"}}}}

But the content I type in never seems to be posted.

I'm trying it out with Chrome 57, Laravel 5.2, and PHP 7.

If I had a non-minified copy of the React I would spend more time trying to suss out the issue, although my React skills are limited; since only the minified versions are in the repo, I'm just going to go ahead and ask for help.

Thanks!

**Comment by mabasic** [comment]
I just tried it with L5.4 and it works as expected. Going to test with L5.2 and let you know

**Comment by mabasic** [comment]
Just tried with L5.2.31 and it works as expected. No errors. Have you followed the readme on Installation?

**Comment by agouticreative** [comment]
Yes I have. Entirely possible I did something wrong. Ha Czech

**Comment by mabasic** [comment]
When you post a comment two request are made. 

- One is a POST request that sends the data. 
- The other is a GET request that loads the comments.

Are you using this syntax in your view to declare your content_type class?

```
@include('comments::comments-react', [
    'content_type' => App\Book::class,
    'content_id' => $book->id
])
```

Try creating a new laravel application, install the package and follow the readme. Then, you can compare what is different in your application. I have tried with L5.2 and 5.4, and it works without a glitch. 

I will be making a video tutorial on how to install this package, maybe that will help you.

P.S. Have you entered the models that can be commented upon in the config?

**Comment by agouticreative** [comment]
If I get the opportunity yes I will do that.
For now I am going to write a vanilla/jQuery adapter for the endpoint. It occured to me that it might be a bit dangerous to deploy a React-based product when I'm not that good at React... Maybe I'll even do a PR if it's something that could be folded in.
The one thing I will say before moving on is that the initial GET to  http://www.xxx.com/api/v1/comments?content_type=App%5CModels%5CExpense&content_id=39 works fine. So that _seems_ to imply that my config is correct. It's just the POSTing of the comment that seems screwy. It really looks like it turns into a param-less GET request. It does seem likely that it's a conflict with something on our end; if I trip over it I will let you know. Thanks.

**Comment by agouticreative** [comment]
Hey I figured it out.
I'm not sure why you aren't seeing it; besides a lack of imagination on my part, or blindness to something about my own env, I have to assume you aren't serving files with apache, or otherwise are overriding the .htaccess file.
Here's what I'm seeing:
the comments-react.js uses `/api/v1/comments/` as a base path
Laravel ships with a /public/.htaccess file with a rewrite rule that removes trailing slashes from non-folder paths
so the store and index actions are getting 301'ed to `/api/v1/comments` (note missing trailing slash)
That's fine for the index call, but it breaks the store call, because when you 301 a POST, it is converted into a GET and the data is lost.
when I remove that trailing slash in comments-react.js, everything works great.

**Comment by mabasic** [comment]
I see. I have created a new release [1.1.1](https://github.com/laravelista/comments/releases/tag/1.1.1) where I removed the trailing slash and modified the URL string for delete and update. Let me know if it works for you.

Remember to publish the latest assets once you upgrade the package:

```
php artisan vendor:publish --provider="Laravelista\Comments\Providers\CommentsServiceProvider" --tag=public --force
```

**Comment by agouticreative** [comment]
great! will try today

**Comment by Ande1232** [comment]
I have the same problem... @agouticreative Did you solve the problem? When I visit the page, I point out that I am not login...

`There are no comments yet. Be the first to comment.
You must login to post a comment.`

**Comment by MohamedELSerag88** [comment]
if i have comments on the model i see this message (There are no comments yet. Be the first to comment. You must login to post a comment.) even i signed in

**Comment by shikakunhq** [comment]
even the problem still persist on latest laravel build

**Comment by walidbagh** [comment]
same problem on laravel 5.5 even on fresh install !
what can we do to help you fix it ?

**Comment by mabasic** [comment]
As soon as I find some time I will fix this issue and all others. I have a solution ready, just need to sit down and code it.

**Comment by walidbagh** [comment]
Great news, thanks for taking time to fix it :1st_place_medal: :) @mabasic

**Comment by G00sfraba** [comment]
I have the same issue here, only that I get 404 error.
http://dev.local.com/api/v1/comments?content_type=App%5CProjectWeek&content_id=9
Status Code: 404 Not Found

**Comment by DaveMG3** [comment]
I got the same issue today end June 2018...thanks to the creator for this lib but you should specify on the main page that the library is broken. I spend 3h to fight with this issue before discovering it was a well known issue.
You should avoid new people to install your library and potentially running again in some time lost
Thanks

**Comment by mabasic** [comment]
I tell you what... I am fixing this this weekend.

**Comment by DaveMG3** [comment]
@mabasic , thank you , my meaning was your library has some potential, maybe you could let other contributors support you to improve it...for now we cant as your native files are not all published, especially react files

**Comment by mabasic** [comment]
Fixed in version [2.0.0](https://github.com/laravelista/comments/releases/tag/2.0.0)

**Comment by DaveMG3** [comment]
Thanks @mabasic ,
Will see if some other users have the same issue but seems v2.0.0 throw 
```
CommentServiceProvider not found 
Script php artisan package:discover handling the post autoload dump event returned with error code 1
```
during Composer require command launched for update of package.

**Comment by mabasic** [comment]
You need to remove CommentServiceProvider from app.php.

This new version uses package discovery to register the service provider.
