### ISSUE TITLE
How to change this config param in config/comment.php

### ISSUE THREAD

**Issue by danhrcvn** [laravelista/comments#60]
I tried to change some param in comments.php like guest_commenting=true, and then I run:
`php artisan vendor:publish --provider="Laravelista\Comments\ServiceProvider" --tag=config.`
 After that in the view page I print the guest_commenting by 
`{{dd(config('comments.approval_required'))}}
` but I was show false. How can I fix that? Thank you very much for your help.

**Comment by mabasic** [comment]
This is the process:

- publish the configuration file: 

```
php artisan vendor:publish --provider="Laravelista\Comments\ServiceProvider" --tag=config
```

In your `config/comments.php` configuration file, change the `approval_required` field to `true`.

It should work. If it does not work le me know.

### Potential issues

If you are using auto-discovery for this package and it still does not work. Try manually adding it to the list of service providers in the `config/app.php` file:

```
\Laravelista\Comments\ServiceProvider::class
```
