### ISSUE TITLE
Help needed

### ISSUE THREAD

**Issue by musawershah1598** [laravelista/comments#65]
How can i use laravelista/comments in order to show latest posted comments on top rather than first comment posted.

**Comment by musawershah1598** [comment]
I have sort this thing i have change the view for comments in vendor folder

**Comment by mabasic** [comment]
Don't ever change things in the vendor folder.

Use this command:

```
php artisan vendor:publish --provider="Laravelista\Comments\ServiceProvider" --tag=views
```

Then modified the published views.
