### ISSUE TITLE
App Engine: Please provide a valid cache path.

### ISSUE THREAD

**Issue by cheing** [laravelista/comments#68]
I had the issue 'Please provide a valid cache path." when deploy.

I found a lot solution from web, and I had did below solution, but the error still occur
1. clear cache
php artisan route:clear
php artisan view:clear
php artisan config:clear
php artisan cache:clear

2. confirm file exist
storage/framework/cache
storage/framework/sessions
storage/framework/views

3. add code to bootstrap/app.php
$app->useStoragePath(env('APP_STORAGE', base_path() . '/storage'));

4. declare APP_STORAGE app.yaml
  APP_STORAGE: /tmp
  VIEW_COMPILED_PATH: /tmp
  SESSION_DRIVER: cookie

**Comment by mabasic** [comment]
Don't know much about App Engine, but take a look at this issue here https://github.com/laravelista/comments/issues/47 where people were discussing it

**Comment by cheing** [comment]
> Don't know much about App Engine, but take a look at this issue here #47 where people were discussing it.

i have saw the post too, but it does't work for me

**Comment by mabasic** [comment]
Sorry, can't help you with this one as it seems to be an App Engine and Laravel issue. I would try googling for "Please provide a valid cache path." in AppEngine and Laravel.

**Comment by cheing** [comment]
> Sorry, can't help you with this one as it seems to be an App Engine and Laravel issue. I would try googling for "Please provide a valid cache path." in AppEngine and Laravel.

Thank i found the solution
run below comment
**php artisan config:cache**

and deploy again it work
