### ISSUE TITLE
Laravelista does not log in

### ISSUE THREAD

**Issue by chrisvwn** [laravelista/comments#7]
Even when logged in my laravelista comments section still shows "You must login to post a comment". Please help me fix this. Laravel 5.4.0/PHP 5.6.29

**Comment by mabasic** [comment]
Sure thing. Can you send me the response from the GET request to `/api/v1/comments?blabla`?

**Comment by chrisvwn** [comment]
Thanks. This is the report I get:

> {"error":{"message":{"content_type":["The content type field is required."],"content_id":["The content id field is required."]},"status_code":422}}

**Comment by mabasic** [comment]
This seems to be a duplicate of https://github.com/laravelista/comments/issues/6

We will continue there. See the last comment in that issue from me and tell me if that works for you.
