### ISSUE TITLE
Hello delete edit and reply not working

### ISSUE THREAD

**Issue by atta1234** [laravelista/comments#71]
403
This action is unauthorized.

**Comment by mabasic** [comment]
Laravel version?

**Comment by atta1234** [comment]
thanks for quick reply sir version is 6.0

**Comment by mabasic** [comment]
Np. Ok, I haven't tested the package with Laravel 6 yet. Need to investigate.

**Comment by atta1234** [comment]
ok i really need this package to work in 6

**Comment by mabasic** [comment]
Just tested with fresh install of `Laravel Framework 6.13.1` and `"laravelista/comments": "^3.1"` and it works. I can edit, reply and delete.
