### ISSUE TITLE
Use this package in Voyager

### ISSUE THREAD

**Issue by ihamedj73** [laravelista/comments#72]
i want to use this package in my project that uses voyager 
in bread voyager there is section call name model what can I add in there 
(sorry my english is so bad :(   )

**Comment by reza-kharestani** [comment]
you should put `Laravelista\Comments\Comment` in the Model.
but there is a problem! when I did that I was able to see a list of comments but when I tried to edit one of them I got an error like this: `403 This action is unauthorized.`

**Comment by reza-kharestani** [comment]
I solved the problem in a very strange way! I think the `.../admin/comments/{comments}` route for the voyager is reserved somehow in another part of the code! I simply changed the slug from `comments` to `commentsss` and It workes fine now!
I don't know if this is a bug in voyager or in `laravelista/comments` so maybe someone can check this out!

**Comment by reza-kharestani** [comment]
There is another issue with commenting on the main site now! I simply made a model class like this:
```
namespace App;

use Illuminate\Database\Eloquent\Model;
use Laravelista\Comments\Events\CommentCreated;
use Laravelista\Comments\Events\CommentUpdated;
use Laravelista\Comments\Events\CommentDeleted;

class Comment extends \Laravelista\Comments\Comment
{

}
```
then in the voyager bread settings, I put ```App\Comment``` as the model name

**Comment by mabasic** [comment]
This sounds like a issue between Voyager and this package. I will close this issue for now since I can't solve this. If you have a solution feel free to share it here or submit a PR so we can talk more.
