### ISSUE TITLE
Separate views for comments list and form?

### ISSUE THREAD

**Issue by dambridge** [laravelista/comments#74]
Hi there, great package. Wondering if there's a simple path to being able to have separate calls to the listing and form views. In my case, I'd like to include the form separately in a fixed div at the bottom of a post, but currently this is not possible with the @comments directive.

**Comment by mabasic** [comment]
Hello, thank you. Yes, it is possible to do this, but it requires some manual steps.

1. [Publish the views](https://github.com/laravelista/comments#publish-views-customization)
2. Stop using `@comments` helper
3. Modify `resources/views/components/comments.blade.php` to include only the comments without the form
4. Modify `resources/views/_form.blade.php` to include auth rules and guest commenting from `comments.blade.php`
5. Use those views directly where you want them.

Hope this helps you.
