### ISSUE TITLE
Compatible with Laravel 6?

### ISSUE THREAD

**Issue by JonPurvis** [laravelista/comments#79]
Hello!

I've been using this package for a while now and recently updated my application to Laravel 6, unfortunately my views no longer show the comment views when using 

`@comments(['model' => $model_name])` and it just shows `(['model' => $model_name])` in my view.

I've managed to find a temporary workaround which render the correct views:

`@include('vendor.comments.components.comments', ['model' => $model_name])` 

I'm just wondering if anyone else can replicate this so I know that it's not just me! 

Thanks

**Comment by mabasic** [comment]
This seems to me that something is not loading right. Update comments to the latest version and go over documentation step by step. I have tested it with Laravel 6 and it works.

Let me know if you solve this.

**Comment by nyl2k8** [comment]
@mabasic Silly question but have you tried clearing the view cache? `php artisan view:clear` I had an issue with the @honeypot directive within Laravista after upgrading but it worked fine after I cleaned the view cache.

**Comment by JonPurvis** [comment]
@nyl2k8 Tried that but just tried it again just incase, still no luck :(

**Comment by JonPurvis** [comment]
This randomly started working again 😆No idea what the actual cause was!
