### ISSUE TITLE
Timezones?

### ISSUE THREAD

**Issue by jmagnuss** [laravelista/comments#8]
I'm in PST but seeing the datetime for each comment in UTC.
Any suggestions on having the UX show the correct timezone?

**Comment by mabasic** [comment]
I'm not quite sure why is that happening... I am in +2 and have no problem with this. Maybe check your server time or set the correct timezone/region in Laravel config/app.php<http://app.php>.

Hope it helps.

---- jmagnuss wrote ----


I'm in PST but seeing the datetime for each comment in UTC.
Any suggestions on having the UX show the correct timezone?

**Comment by jmagnuss** [comment]
I sorted it!  You're right, it was respecting the tz in config/app.php which I hadn't touched.

**Comment by mabasic** [comment]
Happy to help!
