### ISSUE TITLE
Please add support for laravel 7.1.0

### ISSUE THREAD

**Issue by dvlpr-shivendra** [laravelista/comments#81]
I tried to install with Laravel 7.1.0 and it failed with errors
![Screenshot from 2020-03-16 08-09-36](https://user-images.githubusercontent.com/47425193/76718685-85a4a200-675d-11ea-80cf-fd92323b225d.png)

**Comment by mabasic** [comment]
Going to implement Laravel 7 support very soon.

**Comment by marvelbark2** [comment]
not yet ?

**Comment by mabasic** [comment]
> not yet ?

I'm currently working on a new website for a client and hopefully in a few days I will be implementing this package in a Laravel 7.3 application. So, the support for Laravel 7 will be implemented, I just want to be sure that everything works because I already know of a breaking change which will need fixing.

**Comment by futureeducationbr** [comment]
Any updates of Laravel 7.1.0?

Thanks

**Comment by mabasic** [comment]
> Any updates of Laravel 7.1.0?
> 
> Thanks

Not yet. A major refactor of a Laravel 5.8 application got me occupied.

**Comment by CharlesKitonga** [comment]
Heyy, not to add any pressure. Any Updates of Laravel 7 ?? It really is a great package

**Comment by mabasic** [comment]
Thank you. I will try to do it tommorow morning, but can't make promises.

**Comment by dgillier** [comment]
Laravel 7 support plssssss ;))))

**Comment by mabasic** [comment]
Added in `3.5.0`, but I must admit that I haven't tested it yet, so let me know if there are any errors to fix it asap. I'm planning to implement workbench for testing so that I don't have to test everything by hand every time.

**Comment by CharlesKitonga** [comment]
Awesome thank you..
