### ISSUE TITLE
Call to a member function count() on null

### ISSUE THREAD

**Issue by itsmysterybox** [laravelista/comments#82]
I have Commenter trait in User model and Commentable trait in Post model.

In my blade view, I am trying to render comments as follows:
`@comments(['model' => $data['post']])`

Here, `$data` is an array consisting of some objects. `post` is one of them.

When I visit page in browser, I get `Call to a member function count() on null`

![image](https://user-images.githubusercontent.com/43930682/77225649-e33e5180-6b96-11ea-8f2c-1d1c240391e3.png)

**Comment by mabasic** [comment]
I would double check your Post model (the trait Commentable should provide methods: `comments` and `approvedComments`) and what is in your `$data['post']` key (maybe you are not including relationships...).

**Comment by itsmysterybox** [comment]
Ah! I forgot to include comments. Adding `comments` did work.
`$posts = Post::with('tags', 'topic', 'comments')->published()->get();`

Thanks!

**Comment by mabasic** [comment]
Glad to help.
