### ISSUE TITLE
vendor/laravelista/comments/src/ServiceProvider.php:37

### ISSUE THREAD

**Issue by muratozenc** [laravelista/comments#83]
Hi, seems a great package but I could not experience it to say more! When I tried to install it, after the installation got an error on the page.

**Note:** I also use Laravel Voyager as you can see in my composer.json file below. Maybe there is a conflict, so when I comment the line **$this->definePermissions();** from **boot function** in the file **/Users/muratozenc/Documents/code/php/amkp/vendor/laravelista/comments/src/ServiceProvider.php**, system works.

My System;
--------------------------------------------------------------------------------
macOS Catalina
Laravel Framework 6.18.3
PHP 7.2.26
Nginx

Error is following;
--------------------------------------------------------------------------------
Using version ^3.3 for laravelista/comments
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 3 installs, 0 updates, 0 removals
  - Installing erusev/parsedown (1.7.4): Loading from cache
  - Installing spatie/laravel-honeypot (1.5.0): Loading from cache
  - Installing laravelista/comments (3.3.0): Loading from cache
Writing lock file
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi

   ErrorException  : Invalid argument supplied for foreach()

  at /Users/xxx/Documents/code/php/amkp/vendor/laravelista/comments/src/ServiceProvider.php:37
    33|      * Define permission defined in the config.
    34|      */
    35|     protected function definePermissions()
    36|     {
  > 37|         foreach(config('comments.permissions') as $permission => $policy) {
    38|             Gate::define($permission, $policy);
    39|         }
    40|     }
    41|

  Exception trace:

  1   Illuminate\Foundation\Bootstrap\HandleExceptions::handleError("Invalid argument supplied for foreach()", "/Users/xxx/Documents/code/php/amkp/vendor/laravelista/comments/src/ServiceProvider.php", [])
      /Users/xxx/Documents/code/php/amkp/vendor/laravelista/comments/src/ServiceProvider.php:37

  2   Laravelista\Comments\ServiceProvider::definePermissions()
      /Users/xxx/Documents/code/php/amkp/vendor/laravelista/comments/src/ServiceProvider.php:52

  Please use the argument -v to see more details.
Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1

Installation failed, reverting ./composer.json to its original content.
➜  amkp git:(master) ✗ php artisan vendor:publish --provider="Laravelista\Comments\ServiceProvider" --tag=config

   ErrorException  : Invalid argument supplied for foreach()

  at /Users/xxx/Documents/code/php/amkp/vendor/laravelista/comments/src/ServiceProvider.php:37
    33|      * Define permission defined in the config.
    34|      */
    35|     protected function definePermissions()
    36|     {
  > 37|         foreach(config('comments.permissions') as $permission => $policy) {
    38|             Gate::define($permission, $policy);
    39|         }
    40|     }
    41|

  Exception trace:

  1   Illuminate\Foundation\Bootstrap\HandleExceptions::handleError("Invalid argument supplied for foreach()", "/Users/xxx/Documents/code/php/amkp/vendor/laravelista/comments/src/ServiceProvider.php", [])
      /Users/xxx/Documents/code/php/amkp/vendor/laravelista/comments/src/ServiceProvider.php:37

  2   Laravelista\Comments\ServiceProvider::definePermissions()
      /Users/xxx/Documents/code/php/amkp/vendor/laravelista/comments/src/ServiceProvider.php:52

  Please use the argument -v to see more details.

My comoser.json file is like;
--------------------------------------------------------------------------------
{
    "name": "laravel/laravel",
    "type": "project",
    "description": "The Laravel Framework.",
    "keywords": [
        "framework",
        "laravel"
    ],
    "license": "MIT",
    "require": {
        "php": "^7.2",
        "fideloper/proxy": "^4.0",
        "laravel/framework": "^6.2",
        "laravel/tinker": "^2.0",
        "laravel/ui": "^1.2",
        "tcg/voyager": "^1.3"
    },
    "require-dev": {
        "facade/ignition": "^1.4",
        "fzaninotto/faker": "^1.9.1",
        "mockery/mockery": "^1.0",
        "nunomaduro/collision": "^3.0",
        "phpunit/phpunit": "^8.0"
    },
    "config": {
        "optimize-autoloader": true,
        "preferred-install": "dist",
        "sort-packages": true
    },
    "extra": {
        "laravel": {
            "dont-discover": []
        }
    },
    "autoload": {
        "psr-4": {
            "App\\": "app/"
        },
        "classmap": [
            "database/seeds",
            "database/factories"
        ]
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        }
    },
    "minimum-stability": "dev",
    "prefer-stable": true,
    "scripts": {
        "post-autoload-dump": [
            "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
            "@php artisan package:discover --ansi"
        ],
        "post-root-package-install": [
            "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "@php artisan key:generate --ansi"
        ]
    },
    "repositories": {
        "hooks": {
            "type": "composer",
            "url": "https://larapack.io"
        }
    }
}

**Comment by muratozenc** [comment]
It seems about bootstrap cache, closing the issue...

**Comment by mabasic** [comment]
Glad that you have worked it out ❤️
