### ISSUE TITLE
Empty comments

### ISSUE THREAD

**Issue by marvelbark2** [laravelista/comments#84]
Hello 
i have :
 + LaraveL : 6
 + Package : 3.3
My issue is model return with comments attribute empty even the database has comments data 
Please how to fix that ?

**Comment by mabasic** [comment]
See this issue if it helps: https://github.com/laravelista/comments/issues/82

**Comment by mabasic** [comment]
@marvelbark2 Have you solved this?

**Comment by marvelbark2** [comment]
yes but making relationship in my model called comments its seems there's problem in morph relationships issues

**Comment by mabasic** [comment]
Check troubleshoot in the readme if you have upgraded package versions. The trait Commentable and commenter should return comments if everything is configured correctly. Go through the readme again and double check. Also check the table for comments to see what is being used for polymorphism.
