### ISSUE TITLE
Passing requests parameters through CommentController

### ISSUE THREAD

**Issue by mefenlon** [laravelista/comments#86]
I am attempting to pass some request parameters to the CommentController. I have a date selector dropdown which defaults back to initial state after a comment is submitted.

config\comments.php
```
    /**
     * The Comment Controller.
     * Change this to your own implementation of the CommentController.
     * You can use the \Laravelista\Comments\CommentControllerInterface.
     */
    'controller' => 'App\Http\Controllers\MyCommentController',
...
```

_form.blade.php added
```
<form method="POST" action="{{ route('comments.store') }}">
@foreach (request()->except('_token') as $key =>  $item)
            <input type="hidden" name="{{ $key  }}" value="{{ $item }}" />
@endforeach
...
```

App\Http\Controllers\MyCommentController.php is just a copy of vendor\laravelista\comments\src\CommentController.php
but never getting to my dd. Form submits and I am back at the starting page.
```
    /**
     * Creates a new comment for given model.
     */
    public function store(Request $request)
    {
        dd($request);
...
```

I have run php artisan config:clear after making my config changes.
What am I doing wrong here?

If there is an easier way to return to the previous page in the current state, I am open to suggestions.

Thank you for your help.

**Comment by mabasic** [comment]
I need to test if the functionality for swapping controllers works and then I will let you know.

**Comment by mefenlon** [comment]
I may have solved this. After composer update, config:cache, route:cache the routes are now using my controller.

**Comment by mabasic** [comment]
Try `config:clear` and `route:clear` also and see if it works then.
