### ISSUE TITLE
Can you please implement soft deletes as an option

### ISSUE THREAD

**Issue by Riaan-ZA** [laravelista/comments#87]
This would be useful in some cases

**Comment by mabasic** [comment]
Hi, I agree that this would be useful, but I am not planning to implement this. 

If you want to send a PR that would be great, or you can sponsor me/this project on [Patreon](https://www.patreon.com/laravelista) and then I can dedicate some time to implement this.

**Comment by Riaan-ZA** [comment]
Done
#88
