### ISSUE TITLE
Isolated comments for different ID's

### ISSUE THREAD

**Issue by vitormicillo** [laravelista/comments#95]
Greate job here @mabasic , really great job, congrats mate
But,
I am going through something strange, I have applied comments in my posting system but the comments are visible in all posts and not individually for different posts.
For example, range of posts ranging from / posts / 1 to / posts / X
the comments are the same.
is there anything i must pass on to the class to individualize this by id?

Thanks in advance

**Comment by mabasic** [comment]
I've just tested this and it works as it should.

In your view be sure to provide the correct model for which you want to show the posts for:

```
@comments(['model' => $book])
```

Replace `$book` with your unique model. Eg. `$book = Book::find(1);` or `$book = Book::find(2);` .

Also be sure to apply correct traits to the model you want to be able to comment upon.

Also, the package currently only works with model `id` field. If you use a different id column, you have to customize the view `_form.blade.php` to set the correct field to be used. Read the documentation to see how you can customize views.

**Comment by vitormicillo** [comment]
This was a mistake, I was instantiating my class in the wrong way, yes it works perfectly.
cheers mate.

**Comment by vitormicillo** [comment]
But I think it would be interesting if you update your readme with details like this, you can take questions from people just like me.

**Comment by mabasic** [comment]
> But I think it would be interesting if you update your readme with details like this, you can take questions from people just like me.

Maybe in the future, depending on the amount of questions I receive like this.
