### ISSUE TITLE
Undefined property: stdClass::$Comments (View: C:\xampp\htdocs\All Lravel project\swe332\resources\views\vendor\comments\components\comments.blade.php)

### ISSUE THREAD

**Issue by mirdostogir** [laravelista/comments#96]
``@php

    if (isset($approved) and $approved == true) {

        $comments = $model->approvedComments;

    } else {

        $comments = $model->Comments; [get error this line please help me] 

    }

@endphp

 

@if($comments->count() < 1)

    <div class="alert alert-warning">There are no comments yet.</div>

@endif

<ul class="list-unstyled">

    @php

        $comments = $comments->sortBy('created_at');

        if (isset($perPage)) {

            $page = request()->query('page', 1) - 1;

            $parentComments = $comments->where('child_id', '');

            $slicedParentComments = $parentComments->slice($page * $perPage, $perPage);

            $slicedParentCommentsIds = $slicedParentComments->pluck('id')->toArray();

            $comments = $comments

                // Remove parent Comments from comments

                ->whereNotIn('id', $slicedParentCommentsIds)

                // Keep only comments that are related to spliced parent comments.

                // This maybe improves performance?

                ->whereIn('child_id', $slicedParentCommentsIds);

            $grouped_comments = new \Illuminate\Pagination\LengthAwarePaginator(

                $slicedParentComments->merge($comments)->groupBy('child_id'),

                $parentComments->count(),

                $perPage

            );

**Comment by mabasic** [comment]
You are using `$model->Comments` (First letter is uppercase), when you should be using `$model->comments` (lowercase).

**Comment by mirdostogir** [comment]
using $model->comments (lowercase). but get same error

**Comment by mabasic** [comment]
Is the error now about the lowercase or uppercase? Why is it complaining about stdclass? Have you checked that you are passing the correct model.

Have you tried using the default views that came with this package? It looks like you are using your modified views.

**Comment by danruiyot** [comment]
I have the same issue, Any solution yet ?
