### ISSUE TITLE
When using pagination 2nd level children and up are not being displayed

### ISSUE THREAD

**Issue by neeil1990** [laravelista/comments#97]
Hello. we do not get second level children.

`            $comments = $comments
                // Remove parent Comments from comments
                ->whereNotIn(Comment::getKeyName(), $slicedParentCommentsIds)
                // Keep only comments that are related to spliced parent comments.
                // This maybe improves performance?
                ->whereIn('child_id', $slicedParentCommentsIds);
`

Maybe better like that:

`public function comments()
    {
        $model = Tab::findOrFail(int id)

        $parentComments = $this->paginate($model->approvedComments->where('child_id', ''), 2, 1);
        $ParentCommentsIds = $parentComments->pluck('id')->toArray();

        $this->childComments($ParentCommentsIds, $model, $parentComments);
        $grouped_comments = $parentComments->groupBy('child_id');
       
         //all sub comments
        dd($grouped_comments);
    }

    private function childComments($ParentCommentsIds, $model, &$parentComments)
    {
        $comments = $model->approvedComments->whereIn('child_id', $ParentCommentsIds);
        $ParentCommentsIds = $comments->pluck('id')->toArray();
        if($ParentCommentsIds){
            $parentComments = $parentComments->merge($comments);
            $this->childComments($ParentCommentsIds, $model, $parentComments);
        }
    }

    public function paginate($items, $perPage = 15, $page = null, $options = [])
    {
        $page = $page ?: (Paginator::resolveCurrentPage() ?: 1);

        $items = $items instanceof \Illuminate\Database\Eloquent\Collection ? $items : \Illuminate\Database\Eloquent\Collection::make($items);

        return new \Illuminate\Pagination\LengthAwarePaginator($items->forPage($page, $perPage), $items->count(), $perPage, $page, $options);
    }`

Recursive function gets everything under comments

Thanks for the package

**Comment by mabasic** [comment]
Thank you. Nice catch! I haven't used that feature myself except for when I wrote it and I presume that I did not test with deeper levels.

I think that this line is the culprit: https://github.com/laravelista/comments/blob/master/resources/views/components/comments.blade.php#L31

```
->whereIn('child_id', $slicedParentCommentsIds);
```

If I delete that line everything should work.

I will need to test this first ofc. :)

**Comment by mabasic** [comment]
Tested with version 3.6.1 and it works. Let me know if it works for you too.

**Comment by neeil1990** [comment]
it's work. but model will receive child comments all pages

**Comment by mabasic** [comment]
> it's work. but model will receive child comments all pages

I've created a new issue for this.
