### ISSUE TITLE
Delete comments from other users

### ISSUE THREAD

**Issue by Helios14Max** [laravelista/comments#99]
Hi, I am new to Laravel and currently doing a school project. I've found your project on youtube from Andre and I have a problem with the comments of other users on the user's posts. I can reply to users without problem but if I add the same structure of post delete to the comments (with the condition if the post owner is connected and viewing the post) gives me a 403 error. I don't know if I need to some additional changes or something in the existing delete code. Thank you.

**Comment by mabasic** [comment]
Hello,

I need a bit more information about what you are trying to do ... are you using the API endpoints, the provided form, or are you customizing the package?

**Comment by Helios14Max** [comment]
I'm using the provided form. Haven't created any routes or views regarding Laravelista.

**Comment by mabasic** [comment]
Try clearing the config cache with artisan config:clear.

I haven't tested with Laravel 6 lately, but with Laravel 7 it works. I will have to look into it.

**Comment by Helios14Max** [comment]
Didn't worked. Gonna try to explain it better based on the image. I'm logged as the user that created the post and have some comments on my post. I can reply to them but if I want to delete them (which with the @can('delete-comment', $comment) doesn't show up and if I try to do it with the @can it gives me a 403 error). But if I switch to other users I can delete them because the comment is linked to their user

![Sin título](https://user-images.githubusercontent.com/58070806/82448457-065b8380-9aaa-11ea-9b62-8ee692dbb7d0.png)

**Comment by mabasic** [comment]
Ahaa. I see. Well, that is by design. We don't want people to be able to delete other people comments by default.

You will have to change the permission policy for deleting a comment to be true if the user logged in is the user who wrote the post.

Check the config file on how to modify the gate for deleting a comment and view the policy file.

**Comment by Helios14Max** [comment]
I will give it a try. If I succeed I will close the issue and do a little description for anyone who have the same issue as me. I really appreciate the help mate.

**Comment by Helios14Max** [comment]
Sorry if I'm a bit annoying but where is the info about modifying the gate? I did located the files you were referring with CommentPolicy and CommentController.

**Comment by mabasic** [comment]
No problem,

here it is: https://github.com/laravelista/comments/blob/master/config/comments.php#L16-L21

I have have the lines of interest for you.

To make your life simpler you only need to change this line:

```
'delete-comment' => 'Laravelista\Comments\CommentPolicy@delete',
```

And point it to your custom policy method. Something like:

```
<?php

namespace YourNamespace\Something;

use Laravelista\Comments\Comment;

class CustomCommentPolicy
{
    public function delete($user, Comment $comment) : bool
    {
        // Your code logic here
    }
}
```

Then in the config file you would have to place this:

```
'delete-comment' => 'YourNamespace\Something\CustomCommentPolicy@delete',
```

Hope this helps.

**Comment by Helios14Max** [comment]
I understand that this is the solution but right now with the little knowledge I possess I can't figure how to code it to work properly. I'm still trying atm.

**Comment by mabasic** [comment]
Sure thing. Here, read this [Authorization: Supplying Additional Context](https://laravel.com/docs/7.x/authorization#supplying-additional-context), it will help you.

You need to pass the `Post` and inside the method check if the user logged in ID is the same as the Post author ID.

**Comment by Helios14Max** [comment]
> Sure thing. Here, read this [Authorization: Supplying Additional Context](https://laravel.com/docs/7.x/authorization#supplying-additional-context), it will help you.
> 
> You need to pass the `Post` and inside the method check if the user logged in ID is the same as the Post author ID.

Basically that xD. That's the solution. These are the little moments that a rookie like me get motivated to go forward.

**Comment by Helios14Max** [comment]
Okay, I just found out that the thing I've made back then wasn't 100% the right way.

```
class CustomCommentPolicy extends Controller
{
    public function delete($post, Comment $comment) : bool
    {
        if(Auth::id() == $post->id) {   
            $this->authorize('delete-comment', $comment);
            // return $post->getKey() != $comment->commenter_id;
        }
        else {
            return $post->getKey() == $comment->commenter_id;
        }
    }
}
```
By solution I thought that by doing "!=" would have worked and haven't checked out after because I've been implementing Stripe (my bad and mistake for haven't confirmed 100% that I was done). This is what I have done on my CustomPolicy file like you said back then. I've asked my teacher to help me about this but let's just say that he didn't helped me.
